### ISSUE TITLE
FAILED: ninja: 'kernel/xiaomi/msm8937/include/crypto/acompress.h'

### ISSUE THREAD

**Issue by aohanhongzhi** [riceDroid-Devices/android_kernel_xiaomi_msm8937#2]
![Screenshot_select-area_20220504162616](https://user-images.githubusercontent.com/37319319/166658496-99c92015-83c5-4ef4-87d2-c54cc2ab1de6.png)

I get 
https://github.com/EvilAnsh/kernel_xiaomi_santoni/blob/12.0/arch/arm64/configs/santoni_treble_defconfig

and then 

![image](https://user-images.githubusercontent.com/37319319/166658223-e51402c4-f019-4590-b30a-9f2618b1bd30.png)

**Comment by laleeroy** [comment]
Hi, regarding that a friend of mine that build for ulysse managed to complete his build like a few hours ago.
Try to use this instead, 
https://github.com/EvilAnsh/kernel_xiaomi_santoni
